CREATE TABLE IF NOT EXISTS `pvk` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `название` TEXT NOT NULL
);

LOAD DATA LOCAL INFILE 'pvk.csv'
INTO TABLE pvk
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
